general:
  name: cz_induction
  sim_dir: './simdata/_test'  # will be replaced by control
  visualize: False

control:
  setup: './examples/cz_test/setup.py'

geometry:
  mesh:
    size_factor: 3
    order: 1

simulation:
  general:
    transient: true
