general:
  name: cz_induction
  sim_dir: './simdata/_test'  # will be replaced by control
  visualize: False

control:
  setup: 'opencg/nemocrys/test_cz_induction.py'

geometry:
  mesh:
    size_factor: 3
    order: 1

simulation:
